version: '3.8'
services:
  mongodb:
    image: mongo:4.4
    container_name: mongodb
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs-app
    depends_on:
      - mongodb
    ports:
      - '3000:3000'
    environment:
      MONGO_URL: mongodb://mongodb:27017/stagedb
    volumes:
      - .:/usr/src/app # Mount your local code inside the container
      - /usr/src/app/node_modules # Prevent overwriting node_modules
    command: npm run start:dev # Ensure the app runs in watch mode

volumes:
  mongo-data:
